# Array Operations

- **Arithmetic Operations**
- **Broadcasting**
- **Deep and Shallow copy**
- **Matrix Operations**
- **Advance Array Manipulation**
  - Stacking Array
  - Spliting Array

In [1]:
import numpy as np

**Arithmetic Operation**

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(a1)
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [3]:
arr2 = a1 + a2 # size of both array are same
arr2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [9]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [10]:
arr +10

array([20, 30, 40, 50])

In [11]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr2 +10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

**Deep and Shallow copy**

In [13]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
a[4:6]*10

array([50, 60])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
a
b=a
b[0] = 99
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Matrix Operations**

In [26]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [21]:
a *b # its not correct

array([[ 5, 12],
       [21, 32]])

In [27]:
a @ b # multiplication of matrix

array([[19, 22],
       [43, 50]])

In [28]:
np.dot(a,b) # multiplication of matrix

array([[19, 22],
       [43, 50]])

In [34]:
a.T

array([[1, 3],
       [2, 4]])

In [35]:
b.T

array([[5, 7],
       [6, 8]])

**Advance Array Manipulation**

##### *Stacking*

In [49]:
a = np.array([1,2,3,4]) # use vectors not use matrix
b = np.array([5,6,7,8]) 

In [50]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

##### *Spliting array*

In [54]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [56]:
a = np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [57]:
for i in a:
    print(i)

1
2
3
4
