#  Array Indexing and slicing

- NUMPY INDEXING AND SLICING OF VECTOR
- NUMPY INDEXING AND SLICING OF MTRIX
- BOOLEAN INDEXING

In [1]:
import numpy as np

**Numpy indexing and Slicing of vector**

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[8] # indexing

np.int64(19)

In [4]:
# Slicing
arr[1:5]

array([12, 13, 14, 15])

In [5]:
arr[:6] # starts with zero index

array([11, 12, 13, 14, 15, 16])

In [6]:
arr[1:] # end with last index

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr_slice = arr[1::2] # start with 1 and 2 steps
arr_slice

array([12, 14, 16, 18, 20])

In [8]:
arr[2]

np.int64(13)

**Numpy indexing and Slicng of matrix**

In [9]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[0]

array([1, 2, 3, 4, 5])

In [11]:
# indexing
arr[1,3]

np.int64(9)

In [12]:
arr[0,1]

np.int64(2)

In [13]:
# Slicing
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [14]:
slice1 = arr[3:,3:]
slice1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**Boolean indexing**

In [16]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [18]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])