In [1]:
import numpy as np

**Valid Sudoku**

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
]) 
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [3]:
b = np.sum(s,axis = 1)
for i in b:
    if i !=45:
        print("Sudoku is not valid")
        break
else: 
    print("Sudoku for rows it is valid")

Sudoku for rows it is valid


In [4]:
c = np.sum(s, axis = 0)
for i in c:
    if i !=45:
        print("Sudoku is not valid")
        break
else: 
    print("Sudoku for columns it is valid")

Sudoku for columns it is valid


In [5]:
# method 1
slice1 = s[:3,:3]
slice2 = s[3:6,:3]
slice3 = s[6:9,:3]
slice4 = s[:3,3:6]
slice5 = s[3:6,3:6]
slice6 = s[6:9,3:6]
slice7 = s[:3,6:9]
slice8 = s[3:6,6:9]
slice9 = s[6:9,6:9]
a = slice1.sum()
d = slice2.sum()
e = slice3.sum()
f = slice4.sum()
g = slice5.sum()
h = slice6.sum()
i = slice7.sum()
j = slice8.sum()
k = slice9.sum()
t = np.array([a,d,e,f,g,h,i,j,k])
r = t == 45
r

   


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [6]:
# method 2
valid = True
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        m = n.sum()
        if m != 45:
            valid = False

if valid:
    print("Its a valid Sudoku")
else:
    print("Its not a valid Sudoku")

Its a valid Sudoku


**General Question**

In [7]:
import numpy as np

# Columns: [Age, Math MArks, Science Marks]
data = np.array([
    [18, 85, 78], # Student 1
    [19, 92, 88], # Student 2
    [17, 76, 95], # Student 3
    [18, 65, 70], # Student 4
    [20, 90, 85]  # Student 5
]) 
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [8]:
# Get the shape of the matrix.
data.shape

(5, 3)

In [9]:
# Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [10]:
# Extract Math marks of all student.
data[:,1] 

array([85, 92, 76, 65, 90])

In [11]:
# FInd the highest Science marks.
np.max(data[:,2])

np.int64(95)

In [12]:
# Get details of the student who scored more then 90 in Math.
len(data[data[:,1]>90])


1

In [13]:
# Icrease Math marks of all student by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [14]:
# Find how many students are younger then 19.
len(data[data[:,0]<19])

3

In [15]:
# Calculate the average marks in each subject (colmn-wise mean).
np.mean(data[:,1:],axis = 0)

array([86.6, 83.2])

In [16]:
# Get data of students who scored at least 80 in both subject.
data[(data[:,1]>= 80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [17]:
# Replace all Science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])