# Numpy Arrays

- ##### Basic Array creation.
- ##### Array generation function.
- ##### Random Generation function.
- ##### Array Attributes.
- ##### Array Methods.
- ##### Reshaping and resizing.

In [2]:
import numpy as np

**Basic Array creation**

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
a = [1,2,3.5]
a

[1, 2, 3.5]

In [12]:
np.array(a)

array([1. , 2. , 3.5])

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array generation function**

In [19]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [26]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [35]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Random generation function**

In [44]:
np.random.rand(10)

array([0.45225382, 0.74925091, 0.49712001, 0.90681215, 0.55853683,
       0.08874184, 0.66286625, 0.79804833, 0.06593446, 0.55239245])

In [48]:
np.random.randn(10) 

array([ 0.15653632,  0.13616297,  0.93501932, -0.8619845 ,  0.92590113,
        0.03834018, -0.45186966,  1.09549316,  0.13895631,  0.99858931])

In [50]:
np.random.randint(10,20,10)

array([11, 11, 12, 19, 13, 11, 10, 17, 11, 13], dtype=int32)

**Array Attributes**

In [56]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr.shape

(3, 3)

In [58]:
arr.size

9

In [59]:
arr.dtype

dtype('int64')

**Array Methods**

In [60]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr.min()

np.int64(1)

In [62]:
arr.max()

np.int64(9)

In [64]:
arr.sum()

np.int64(45)

In [69]:
np.sum(arr, axis = 0) # axis 0 for column

array([12, 15, 18])

In [70]:
np.sum(arr, axis = 1) # axis 1 for row

array([ 6, 15, 24])

In [71]:
arr.mean()

np.float64(5.0)

In [72]:
arr.std()

np.float64(2.581988897471611)

In [73]:
np.mean(arr, axis = 1)

array([2., 5., 8.])

In [74]:
arr.argmax()

np.int64(8)

In [75]:
arr.argmin()

np.int64(0)

**Reshaping and resizing**

In [78]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [82]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])